/**
 * 最小 sRGB ICC プロファイルの生成（B-8 = PDF/A-3b の OutputIntent 用）
 *
 * ## なぜ生成するのか（同梱でもダウンロードでもなく）
 *
 * PDF/A の OutputIntent は `DestOutputProfile` に **ICC プロファイルストリーム**を要求する
 * （ISO 32000-1 Table 365。形式は ICCBased 色空間と同じ = §8.6.5.5）。
 * 選択肢は 3 つあったが、生成を採った:
 *
 * 1. **ICC ファイルを同梱** — バイナリ資産をリポジトリに持ち込むことになり、
 *    再配布ライセンスの確認が必要（Apple / Adobe / ICC で条件が違う）。
 * 2. **実行時にダウンロード** — オフラインで壊れる。決定論（E-6）も崩れる。
 * 3. **生成**（採用）— 外部依存ゼロ・オフラインで動く・**バイト列が固定なので E-6 と両立**。
 *
 * ## 何を作るか
 *
 * ICC v2 の **matrix/TRC 方式の display class（'mntr'）RGB プロファイル**。
 * ICC v2 がこのクラスに要求する必須タグだけを持つ:
 * `desc` / `cprt` / `wtpt` / `rXYZ` / `gXYZ` / `bXYZ` / `rTRC` / `gTRC` / `bTRC`。
 *
 * 原色と白色点は **sRGB（IEC 61966-2.1）を D50 に色順応させた標準値**。
 * ICC の PCS は常に D50 なので、D65 の sRGB 原色をそのまま書いてはいけない。
 *
 * ## 既知の割り切り: TRC をガンマ 2.2 で近似している
 *
 * sRGB の真の伝達関数は**線形部分を持つ区分関数**（暗部が線形・以降が 2.4 乗）であり、
 * 単一のガンマ値では表せない。ここでは `curveType` の count=1（= u8Fixed8 のガンマ 1 個）で
 * **2.2 に近似**している。実務上の誤差は暗部に限られ、PDF/A の目的（DeviceRGB を
 * device independent に紐付けて長期保存で色を再現可能にする）は満たす。
 *
 * より正確にしたい場合は count>1 の 1024 点テーブルに差し替える（この関数の中だけで済む）。
 * **精度が要件になったら差し替える**という判断であり、条文上の要求ではない。
 */

/** s15Fixed16Number（ICC の固定小数点。1.0 = 0x00010000） */
function s15Fixed16(value: number): number {
  return Math.round(value * 65536);
}

function writeUint32(buf: Uint8Array, offset: number, value: number): void {
  buf[offset] = (value >>> 24) & 0xff;
  buf[offset + 1] = (value >>> 16) & 0xff;
  buf[offset + 2] = (value >>> 8) & 0xff;
  buf[offset + 3] = value & 0xff;
}

function writeUint16(buf: Uint8Array, offset: number, value: number): void {
  buf[offset] = (value >>> 8) & 0xff;
  buf[offset + 1] = value & 0xff;
}

function writeAscii(buf: Uint8Array, offset: number, text: string): void {
  for (let i = 0; i < text.length; i++) buf[offset + i] = text.charCodeAt(i) & 0xff;
}

/** ICC タグ 1 件（データは 4 バイト境界に整列させて連結する） */
interface IccTag {
  signature: string;
  data: Uint8Array;
}

/** XYZType（'XYZ ' + reserved + XYZNumber） */
function xyzTag(x: number, y: number, z: number): Uint8Array {
  const data = new Uint8Array(20);
  writeAscii(data, 0, 'XYZ ');
  writeUint32(data, 8, s15Fixed16(x));
  writeUint32(data, 12, s15Fixed16(y));
  writeUint32(data, 16, s15Fixed16(z));
  return data;
}

/** curveType（count=1 のとき u8Fixed8 のガンマ 1 個） */
function gammaCurveTag(gamma: number): Uint8Array {
  const data = new Uint8Array(14);
  writeAscii(data, 0, 'curv');
  writeUint32(data, 8, 1);
  writeUint16(data, 12, Math.round(gamma * 256));
  return data;
}

/**
 * textDescriptionType（ICC v2 の 'desc' 専用型）。
 * ASCII 部のあとに Unicode 部（言語コード + 長さ）と ScriptCode 部（コード + 長さ + 67 バイト固定）が続く。
 * Unicode / ScriptCode は使わないので 0 埋めだが、**領域自体は省略できない**。
 */
function descriptionTag(text: string): Uint8Array {
  const ascii = `${text}\0`;
  // 8（型 + reserved）+ 4（ASCII 長）+ ASCII + 4 + 4（Unicode）+ 2 + 1 + 67（ScriptCode）
  const data = new Uint8Array(8 + 4 + ascii.length + 8 + 70);
  writeAscii(data, 0, 'desc');
  writeUint32(data, 8, ascii.length);
  writeAscii(data, 12, ascii);
  return data;
}

/** textType（'text' + reserved + null 終端 ASCII） */
function textTag(text: string): Uint8Array {
  const ascii = `${text}\0`;
  const data = new Uint8Array(8 + ascii.length);
  writeAscii(data, 0, 'text');
  writeAscii(data, 8, ascii);
  return data;
}

/** OutputConditionIdentifier / Info に使う条件名（ICC Characterization Data Registry の慣用名） */
export const SRGB_CONDITION_IDENTIFIER = 'sRGB IEC61966-2.1';

/**
 * sRGB の ICC プロファイルを組み立てて返す。
 *
 * **同一入力に対して常に同一バイト列**（日時フィールドは 0 埋め、内容に時刻を含めない）。
 * これにより `SOURCE_DATE_EPOCH` による決定論的出力（E-6）を壊さない。
 */
export function buildSrgbIccProfile(): Uint8Array {
  // sRGB（IEC 61966-2.1）の原色を D50 に色順応させた値。ICC の PCS は常に D50 なので、
  // D65 の sRGB 原色をそのまま書くと白が転ぶ
  const tags: IccTag[] = [
    { signature: 'desc', data: descriptionTag(SRGB_CONDITION_IDENTIFIER) },
    {
      signature: 'cprt',
      data: textTag('Generated by @shuji-bonji/pdf-writer-mcp. No rights reserved.'),
    },
    { signature: 'wtpt', data: xyzTag(0.9642, 1.0, 0.82491) },
    { signature: 'rXYZ', data: xyzTag(0.43607, 0.22249, 0.01392) },
    { signature: 'gXYZ', data: xyzTag(0.38515, 0.71687, 0.09708) },
    { signature: 'bXYZ', data: xyzTag(0.14307, 0.06061, 0.7141) },
    { signature: 'rTRC', data: gammaCurveTag(2.2) },
    { signature: 'gTRC', data: gammaCurveTag(2.2) },
    { signature: 'bTRC', data: gammaCurveTag(2.2) },
  ];

  const HEADER_SIZE = 128;
  const tableSize = 4 + tags.length * 12;
  const align4 = (n: number) => (n + 3) & ~3;

  // タグデータの配置を先に決める（オフセットをタグテーブルへ書く必要があるため）
  let cursor = align4(HEADER_SIZE + tableSize);
  const placed = tags.map((tag) => {
    const offset = cursor;
    cursor = align4(cursor + tag.data.length);
    return { ...tag, offset };
  });

  const total = cursor;
  const profile = new Uint8Array(total);

  // --- ヘッダー（128 バイト）---
  writeUint32(profile, 0, total); // プロファイル全体のサイズ
  // 4-7 CMM type: 0（特定の CMM を要求しない）
  writeUint32(profile, 8, 0x02400000); // version 2.4
  writeAscii(profile, 12, 'mntr'); // device class: display
  writeAscii(profile, 16, 'RGB '); // data colour space
  writeAscii(profile, 20, 'XYZ '); // PCS
  // 24-35 日時: 0 埋め（E-6 決定論。時刻を焼くとバイト列が揺れる）
  writeAscii(profile, 36, 'acsp'); // profile file signature
  // 40-43 platform / 44-47 flags / 48-51 manufacturer / 52-55 model / 56-63 attributes: 0
  writeUint32(profile, 64, 0); // rendering intent: 0 = perceptual
  // 68-79 PCS illuminant: D50（ICC 仕様が固定値として定める）
  writeUint32(profile, 68, s15Fixed16(0.9642));
  writeUint32(profile, 72, s15Fixed16(1.0));
  writeUint32(profile, 76, s15Fixed16(0.82491));
  // 80-83 creator / 84-99 profile ID（v4 のみ）/ 100-127 reserved: 0

  // --- タグテーブル ---
  writeUint32(profile, HEADER_SIZE, tags.length);
  placed.forEach((tag, i) => {
    const entry = HEADER_SIZE + 4 + i * 12;
    writeAscii(profile, entry, tag.signature);
    writeUint32(profile, entry + 4, tag.offset);
    writeUint32(profile, entry + 8, tag.data.length);
  });

  // --- タグデータ ---
  for (const tag of placed) profile.set(tag.data, tag.offset);

  return profile;
}
